/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package parser_combinator

import parser_combinator.compile.Compiler

class Library(args: Array[String]) {

  def launch(): Boolean = {
    val answers = args.map(arg ⇒ Compiler.parseFunction(arg))
    print(answers)
    true
  }
}

object Library {

  def main(args: Array[String]): Unit =
    new Library(getSamples).launch()

  def getSamples : Array[String] = {
    val sample1 =
"""
def foo(a: Int, b: Int, c: Int) : Int = {
  let d = a + b * c;
  let e = a + b + d;
  return e;
}
"""
    val sample2 =
      """
def foo(a: Int, b: Int, c: Int) : Int = {
  let d = a > b and c > a + b;
  return d;
}
"""
    Array(sample1, sample2)
  }
}
